catalogMode: prefer
cleanupUnusedCatalogs: true

shamefullyHoist: true
strictPeerDependencies: false

shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - langium@3.3.1

packages:
  - apps/*
  - packages/*

overrides:
  nuxt: 4.4.6
  oxc-parser: 0.102.0
  semver: 7.7.3

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@commitlint/cli': ^21.0.2
  '@commitlint/config-conventional': ^21.0.2
  '@lucide/vue': ^1.17.0
  '@rive-app/webgl2': ^2.38.0
  '@takumi-rs/core': ^1.7.0
  '@vitest/ui': 4.1.8
  '@vue/test-utils': ^2.4.11
  '@vueuse/core': ^14.3.0
  ai: ^6.0.197
  baseline-browser-mapping: ^2.10.34
  bumpp: ^11.1.0
  eslint: ^10.4.1
  h3: ^1.15.11
  lint-staged: ^17.0.7
  media-chrome: ^4.19.1
  motion-v: ^2.2.1
  reka-ui: ^2.9.9
  shadcn-nuxt: 2.7.4
  shadcn-vue: ^2.7.4
  shiki: ^4.2.0
  tailwindcss: ^4.3.0
  ts-morph: ^28.0.0
  typescript: ^6.0.3
  vue: ^3.5.35
  vue-router: ^5.1.0
  vue-sonner: ^2.0.9
  vue-stick-to-bottom: ^1.0.0
  vue-stream-markdown: 1.0.0-beta.5
  wrangler: ^4.98.0
  zod: ^4.4.3

allowedDeprecatedVersions:
  '@oxc-parser/wasm': 0.60.0
  '@types/parse-path': 7.1.0
  glob: 7.2.3
  inflight: 1.0.6
  node-domexception: 1.0.0
  source-map-resolve: 0.6.0

peerDependencyRules:
  allowedVersions:
    zod: '4'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  maplibre-gl: true
  sharp: true
  simple-git-hooks: true
  vue-demi: true
  workerd: true
