catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - langium@3.3.1

packages:
  - apps/*
  - packages/*

overrides:
  semver: 7.7.3

catalog:
  '@rive-app/webgl2': ^2.35.0
  '@vueuse/core': ^14.1.0
  ai: ^6.0.49
  lucide-vue-next: ^0.555.0
  reka-ui: ^2.8.0
  shiki: ^3.20.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vue: ^3.5.25
  vue-sonner: ^2.0.9
  zod: ^4.1.13

allowedDeprecatedVersions:
  '@oxc-parser/wasm': 0.60.0
  '@types/parse-path': 7.1.0
  glob: 7.2.3
  inflight: 1.0.6
  node-domexception: 1.0.0
  source-map-resolve: 0.6.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - sharp
  - simple-git-hooks
  - vue-demi
  - workerd

peerDependencyRules:
  allowedVersions:
    zod: '4'
